/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as NovelNovelIdRouteImport } from './routes/novel.$novelId'
import { Route as NovelNovelIdIndexRouteImport } from './routes/novel.$novelId.index'
import { Route as NovelNovelIdWriteRouteImport } from './routes/novel.$novelId.write'
import { Route as NovelNovelIdReviewRouteImport } from './routes/novel.$novelId.review'
import { Route as NovelNovelIdPlanRouteImport } from './routes/novel.$novelId.plan'
import { Route as NovelNovelIdChatRouteImport } from './routes/novel.$novelId.chat'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelNovelIdRoute = NovelNovelIdRouteImport.update({
  id: '/novel/$novelId',
  path: '/novel/$novelId',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelNovelIdIndexRoute = NovelNovelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NovelNovelIdRoute,
} as any)
const NovelNovelIdWriteRoute = NovelNovelIdWriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => NovelNovelIdRoute,
} as any)
const NovelNovelIdReviewRoute = NovelNovelIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => NovelNovelIdRoute,
} as any)
const NovelNovelIdPlanRoute = NovelNovelIdPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => NovelNovelIdRoute,
} as any)
const NovelNovelIdChatRoute = NovelNovelIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => NovelNovelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/settings': typeof SettingsRoute
  '/novel/$novelId': typeof NovelNovelIdRouteWithChildren
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/novel/$novelId/chat': typeof NovelNovelIdChatRoute
  '/novel/$novelId/plan': typeof NovelNovelIdPlanRoute
  '/novel/$novelId/review': typeof NovelNovelIdReviewRoute
  '/novel/$novelId/write': typeof NovelNovelIdWriteRoute
  '/novel/$novelId/': typeof NovelNovelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/settings': typeof SettingsRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/novel/$novelId/chat': typeof NovelNovelIdChatRoute
  '/novel/$novelId/plan': typeof NovelNovelIdPlanRoute
  '/novel/$novelId/review': typeof NovelNovelIdReviewRoute
  '/novel/$novelId/write': typeof NovelNovelIdWriteRoute
  '/novel/$novelId': typeof NovelNovelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/settings': typeof SettingsRoute
  '/novel/$novelId': typeof NovelNovelIdRouteWithChildren
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/novel/$novelId/chat': typeof NovelNovelIdChatRoute
  '/novel/$novelId/plan': typeof NovelNovelIdPlanRoute
  '/novel/$novelId/review': typeof NovelNovelIdReviewRoute
  '/novel/$novelId/write': typeof NovelNovelIdWriteRoute
  '/novel/$novelId/': typeof NovelNovelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/settings'
    | '/novel/$novelId'
    | '/series/$seriesId'
    | '/novel/$novelId/chat'
    | '/novel/$novelId/plan'
    | '/novel/$novelId/review'
    | '/novel/$novelId/write'
    | '/novel/$novelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/settings'
    | '/series/$seriesId'
    | '/novel/$novelId/chat'
    | '/novel/$novelId/plan'
    | '/novel/$novelId/review'
    | '/novel/$novelId/write'
    | '/novel/$novelId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/settings'
    | '/novel/$novelId'
    | '/series/$seriesId'
    | '/novel/$novelId/chat'
    | '/novel/$novelId/plan'
    | '/novel/$novelId/review'
    | '/novel/$novelId/write'
    | '/novel/$novelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  SettingsRoute: typeof SettingsRoute
  NovelNovelIdRoute: typeof NovelNovelIdRouteWithChildren
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$novelId': {
      id: '/novel/$novelId'
      path: '/novel/$novelId'
      fullPath: '/novel/$novelId'
      preLoaderRoute: typeof NovelNovelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$novelId/': {
      id: '/novel/$novelId/'
      path: '/'
      fullPath: '/novel/$novelId/'
      preLoaderRoute: typeof NovelNovelIdIndexRouteImport
      parentRoute: typeof NovelNovelIdRoute
    }
    '/novel/$novelId/write': {
      id: '/novel/$novelId/write'
      path: '/write'
      fullPath: '/novel/$novelId/write'
      preLoaderRoute: typeof NovelNovelIdWriteRouteImport
      parentRoute: typeof NovelNovelIdRoute
    }
    '/novel/$novelId/review': {
      id: '/novel/$novelId/review'
      path: '/review'
      fullPath: '/novel/$novelId/review'
      preLoaderRoute: typeof NovelNovelIdReviewRouteImport
      parentRoute: typeof NovelNovelIdRoute
    }
    '/novel/$novelId/plan': {
      id: '/novel/$novelId/plan'
      path: '/plan'
      fullPath: '/novel/$novelId/plan'
      preLoaderRoute: typeof NovelNovelIdPlanRouteImport
      parentRoute: typeof NovelNovelIdRoute
    }
    '/novel/$novelId/chat': {
      id: '/novel/$novelId/chat'
      path: '/chat'
      fullPath: '/novel/$novelId/chat'
      preLoaderRoute: typeof NovelNovelIdChatRouteImport
      parentRoute: typeof NovelNovelIdRoute
    }
  }
}

interface NovelNovelIdRouteChildren {
  NovelNovelIdChatRoute: typeof NovelNovelIdChatRoute
  NovelNovelIdPlanRoute: typeof NovelNovelIdPlanRoute
  NovelNovelIdReviewRoute: typeof NovelNovelIdReviewRoute
  NovelNovelIdWriteRoute: typeof NovelNovelIdWriteRoute
  NovelNovelIdIndexRoute: typeof NovelNovelIdIndexRoute
}

const NovelNovelIdRouteChildren: NovelNovelIdRouteChildren = {
  NovelNovelIdChatRoute: NovelNovelIdChatRoute,
  NovelNovelIdPlanRoute: NovelNovelIdPlanRoute,
  NovelNovelIdReviewRoute: NovelNovelIdReviewRoute,
  NovelNovelIdWriteRoute: NovelNovelIdWriteRoute,
  NovelNovelIdIndexRoute: NovelNovelIdIndexRoute,
}

const NovelNovelIdRouteWithChildren = NovelNovelIdRoute._addFileChildren(
  NovelNovelIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  SettingsRoute: SettingsRoute,
  NovelNovelIdRoute: NovelNovelIdRouteWithChildren,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
